/Users/zachzahos/Documents/Projects/PyMS/Libs/MPQ/rez/stat_txt.tbl
/Users/zachzahos/Documents/Projects/PyMS/Libs/MPQ/rez/stat_txt.tbl
/Users/zachzahos/Documents/Projects/PyMS/Libs/MPQ/rez/stat_txt.tbl
/Users/zachzahos/Documents/Projects/PyMS/Libs/MPQ/rez/stat_txt.tbl
/Users/zachzahos/Documents/Projects/PyMS/Libs/MPQ/rez/images.tbl
/Users/zachzahos/Documents/Projects/PyMS/Libs/MPQ/rez/sfxdata.tbl
/Users/zachzahos/Documents/Projects/PyMS/Libs/MPQ/rez/stat_txt.tbl
/Users/zachzahos/Documents/Projects/PyMS/Libs/MPQ/rez/sfxdata.tbl
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
TypeError: search() takes exactly 1 argument (2 given)
